version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: akshakak
    ports:
      - "5432:5432"